# Base configs
baseurl: "."
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Japanese Gardens"
subtitle: "Visiting and documenting the japanese gardens!"
author: "Phenomenal Panda"
header:
 title: "Other Japanese Gardens"
 subtitle: "by Phenomenal Panda"
footer:
 name: "Hey there, my name is Justin"
 bio: "I am a Data Scientist by day. Enjoy experiencing Japanese Gardens, and so I take pictures of them. The attention to detail and recreation of the 'feel' of nature on a small scale is aesthetically pleasing. The entire experience of a garden, from visaul elements to sounds are what makes them great."
 #github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: ""
social_urls:
  #facebook: "https://www.facebook.com/ramswaroop"
  #twitter: "https://www.twitter.com/ram__patra"
  #instagram: "https://www.instagram.com/ram_patra"
  #dribbble: "https://dribbble.com/rampatra"
  #linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/PhenomenalPanda"
